version: '3'

services:
  php:
    container_name: "dootask-php-${APP_ID}"
    image: "kuaifan/php:swoole-8.0"
    shm_size: "1024m"
    volumes:
      - ./docker/crontab/crontab.conf:/etc/supervisor/conf.d/crontab.conf
      - ./docker/php/php.conf:/etc/supervisor/conf.d/php.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/log/supervisor:/var/log/supervisor
      - ./:/var/www
    environment:
      TZ: "Asia/Shanghai"
      LANG: "C.UTF-8"
      MODE: "production"
      MYSQL_HOST: "${DB_HOST}"
      MYSQL_PORT: "${DB_PORT}"
      MYSQL_DB_NAME: "${DB_DATABASE}"
      MYSQL_USERNAME: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      extnetwork:
        ipv4_address: "${APP_IPPR}.2"
    depends_on:
      - redis
      - mariadb
    restart: unless-stopped

  nginx:
    container_name: "dootask-nginx-${APP_ID}"
    image: "nginx:alpine"
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./public:/var/www/public
    environment:
      TZ: "Asia/Shanghai"
    networks:
      extnetwork:
        ipv4_address: "${APP_IPPR}.3"
    links:
      - php
      - office
      - fileview
      - drawio-webapp
      - drawio-export
    restart: unless-stopped

  redis:
    container_name: "dootask-redis-${APP_ID}"
    image: "redis:alpine"
    environment:
      TZ: "Asia/Shanghai"
    networks:
      extnetwork:
        ipv4_address: "${APP_IPPR}.4"
    restart: unless-stopped

  mariadb:
    container_name: "dootask-mariadb-${APP_ID}"
    image: "mariadb"
    ports:
      # mysql ports item
      - "33062:3306" # mysql ports value
    volumes:
      - ./docker/mysql/repassword.sh:/etc/mysql/repassword.sh
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_PREFIX: "${DB_PREFIX}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      extnetwork:
        ipv4_address: "${APP_IPPR}.5"
    restart: unless-stopped

  office:
    container_name: "dootask-office-${APP_ID}"
    image: "onlyoffice/documentserver:7.0.0.132"
    environment:
      TZ: "Asia/Shanghai"
    networks:
      extnetwork:
        ipv4_address: "${APP_IPPR}.6"
    restart: unless-stopped

  fileview:
    container_name: "dootask-fileview-${APP_ID}"
    image: "kuaifan/fileview:4.1.0-SNAPSHOT-RC3"
    environment:
      TZ: "Asia/Shanghai"
      KK_CONTEXT_PATH: "/fileview"
    networks:
      extnetwork:
        ipv4_address: "${APP_IPPR}.7"
    restart: unless-stopped

  drawio-webapp:
    container_name: "dootask-drawio-webapp-${APP_ID}"
    image: "jgraph/drawio:16.6.1"
    networks:
      extnetwork:
        ipv4_address: "${APP_IPPR}.8"
    environment:
      TZ: "Asia/Shanghai"
    depends_on:
      - drawio-export
    restart: unless-stopped

  drawio-export:
    container_name: "dootask-drawio-export-${APP_ID}"
    image: "jgraph/export-server"
    networks:
      extnetwork:
        ipv4_address: "${APP_IPPR}.9"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./docker/drawio/export/fonts:/usr/share/fonts/drawio
    restart: unless-stopped

networks:
  extnetwork:
    ipam:
      config:
        - subnet: "172.68.0.0/24"
